### ISSUE TITLE
Improve textual representation of zval to improve the '.dump' filter pertinence

### ISSUE THREAD

**Issue by buixor** [nbs-system/snuffleupagus#50] opened 2017-10-25 11:29 UTC
`sp_convert_to_string`, used for getting a textual representation of zval should be improved, as it will impact `.dump()`'s pertinence :
- [ ] recursion on arrays
  - [ ] Handle circular references
- [ ]  At least object type for objects
  - [ ] Maybe something à la `var_dump`?

**Comment by jvoisin** [comment] 2017-11-24 16:20
Duplicate of #42

**Closed by jvoisin** 2017-11-24 16:20 UTC
Labels: enhancement, hard, suggestion
